"""Emit the mock-seed migration from seed/users.json.

A migration is static SQL and cannot read a JSON file, so the SQL is generated
rather than hand-written — otherwise seed/users.json and the database drift the
moment one is edited. Regenerate with:

    python3 scripts/gen_seed_migration.py

The artist corpus is derived from the profiles themselves (every artist anyone
lists, with its rank), so it cannot disagree with the rows that reference it.
"""

import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SEED = ROOT / "seed" / "users.json"
OUT = ROOT / "supabase" / "migrations" / "20260804000003_seed_mock.sql"

# Tags per artist, mirroring scripts/gen_v2_seed.py. Kept here too so the corpus
# rows carry genre data without importing that script's private tables.
ARTIST_TAGS = {
    "Grouper": ["ambient", "drone", "slowcore"],
    "Duster": ["slowcore", "lo-fi", "shoegaze"],
    "Alex G": ["indie rock", "lo-fi", "folk"],
    "Adrianne Lenker": ["indie folk", "folk"],
    "Yves Tumor": ["art rock", "experimental"],
    "Cocteau Twins": ["dream pop", "shoegaze"],
    "Burial": ["ambient", "electronic"],
    "Fiona Apple": ["art rock", "singer-songwriter"],
    "Dean Blunt": ["experimental", "art rock"],
    "Arca": ["experimental", "electronic"],
    "Tirzah": ["electronic", "soul"],
    "Beach House": ["dream pop", "shoegaze"],
    "Slowdive": ["shoegaze", "dream pop"],
    "My Bloody Valentine": ["shoegaze", "noise"],
    "Sufjan Stevens": ["indie folk", "folk"],
    "Weyes Blood": ["indie folk", "dream pop"],
    "Mazzy Star": ["dream pop", "folk"],
    "Japanese Breakfast": ["indie pop", "dream pop"],
    "Big Thief": ["indie folk", "folk"],
}


def lit(value) -> str:
    """A SQL literal. Strings are dollar-quoted — the copy is full of apostrophes."""
    if value is None:
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return f"$q${value}$q$"


def jsonb(value) -> str:
    if value is None:
        return "null"
    return f"$q${json.dumps(value, ensure_ascii=False)}$q$::jsonb"


def text_array(values) -> str:
    if not values:
        return "'{}'::text[]"
    inner = ", ".join(f"$q${v}$q$" for v in values)
    return f"array[{inner}]::text[]"


def smallint_array(values) -> str:
    if not values:
        return "'{}'::smallint[]"
    return "array[" + ", ".join(str(int(v)) for v in values) + "]::smallint[]"


data = json.loads(SEED.read_text())
people = data["users"]

# Every artist anyone lists, with its rank. Ranks are globally consistent in the
# seed; assert rather than silently pick one, because a mismatch would quietly
# corrupt rarity for everybody.
corpus: dict[str, int] = {}
for profile in [data["me"], *people]:
    for artist in profile["topArtists"]:
        name, rank = artist["name"], artist["rank"]
        if name in corpus and corpus[name] != rank:
            raise SystemExit(
                f"inconsistent rank for {name}: {corpus[name]} vs {rank} — refusing to write"
            )
        corpus[name] = rank

missing = sorted(set(corpus) - set(ARTIST_TAGS))
if missing:
    raise SystemExit(f"artists with no tags mapped, refusing to write: {missing}")

lines: list[str] = [
    "-- Mock seed: the six candidate profiles and the artist corpus they imply.",
    "--",
    "-- GENERATED by scripts/gen_seed_migration.py from seed/users.json.",
    "-- Do not hand-edit; edit the seed and regenerate.",
    "--",
    "-- Idempotent: re-running updates in place rather than duplicating, so this is",
    "-- safe to apply against a database that already holds an earlier version.",
    "",
    "-- ── artist corpus ──",
    "insert into public.artists_corpus (name, popularity, tags) values",
]

corpus_rows = [
    f"  ({lit(name)}, {rank}, {text_array(ARTIST_TAGS[name])})"
    for name, rank in sorted(corpus.items(), key=lambda kv: kv[1])
]
lines.append(",\n".join(corpus_rows))
lines.append(
    "on conflict (name) do update set\n"
    "  popularity = excluded.popularity,\n"
    "  tags = excluded.tags;"
)
lines.append("")
lines.append("-- ── the six candidates ──")

for person in people:
    notes = {"hours": person["hoursNote"], "rarity": person["rarityNote"]}
    cols = [
        ("slug", lit(person["id"])),
        ("name", lit(person["name"])),
        ("age", lit(person["age"])),
        ("campus", lit(person.get("campus"))),
        ("archetype", jsonb(person["archetype"])),
        ("week", jsonb(person["week"])),
        ("top_artists", jsonb(person["topArtists"])),
        ("top_tracks", jsonb(person["topTracks"])),
        ("listening_hours", smallint_array(person["listeningHours"])),
        ("tags", text_array(person["tags"])),
        ("energy", jsonb(person["energy"])),
        ("reason", lit(person["reason"])),
        ("reason_soft", lit(person["reasonSoft"])),
        ("chips", jsonb(person["chips"])),
        ("line", lit(person["line"])),
        ("flirt", lit(person["flirt"])),
        ("song", jsonb(person["song"])),
        ("notes", jsonb(notes)),
        ("quiz", jsonb(person["quiz"])),
        ("swap", jsonb(person["swap"])),
        ("take_answer", lit(person["takeAnswer"])),
        ("opening_thread", jsonb(person["thread"])),
        ("is_mock", "true"),
        ("liked_you", lit(person["likedYou"])),
    ]

    names = ", ".join(c for c, _ in cols)
    values = ",\n  ".join(v for _, v in cols)
    updates = ",\n  ".join(f"{c} = excluded.{c}" for c, _ in cols if c != "slug")

    lines.append("")
    lines.append(f"insert into public.profiles ({names}) values (\n  {values}\n)")
    lines.append(f"on conflict (slug) do update set\n  {updates};")

lines.append("")
OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines))

print(f"wrote {OUT.relative_to(ROOT)}")
print(f"  {len(people)} profiles, {len(corpus)} artists")
print(f"  liked_you: {[p['name'] for p in people if p['likedYou']]}")
